apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver-depl
  template:
    metadata:
      labels:
        app: webserver-depl
    spec:
      containers:
      - name: webserver-depl
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
