apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp-mystatefulset
  serviceName: myapp-mystatefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-mystatefulset
    spec:
      containers:
      - name: myapp-mystatefulset
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
