---
# Source: airflow/templates/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-airflow
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: airflow
    app.kubernetes.io/version: 2.10.3
    helm.sh/chart: airflow-21.5.1
type: Opaque
data:
  airflow-password: "V3NCNUx1RGg5MA=="
  # Airflow keys must be base64-encoded, hence we need to pipe to 'b64enc' twice
  # The auto-generation mechanism available at "common.secrets.passwords.manage" isn't compatible with encoding twice
  # Therefore, we can only use this function if the secret already exists
  airflow-fernet-key: "VTB0Nk1HUkZaMmhrWWtoaFpFTk9jVGRVZFcxb05UZzBZbVIxYVZWT05tND0="
  airflow-secret-key: "ZGtGWVNsSXhaM1ZyYlhsRmJHa3pWbGt3T1ROc1NuQk1lWFZGUVd4QlNrZz0="
