---
# Source: airflow/templates/secrets/webserver-secret-key-secret.yaml
############################################
## Airflow Webserver Flask Secret Key Secret
############################################

apiVersion: v1
kind: Secret
metadata:
  name: release-name-webserver-secret-key
  labels:
    tier: airflow
    component: webserver
    release: release-name
    chart: airflow
    heritage: Helm
type: Opaque
data:
  webserver-secret-key: "YVc1dlVrMXJjR2hUZFRoWVNVSlBlRFJVVnpFelkyTnVUbUp3T1ZWWVRtMD0="
