---
# Source: airflow/templates/webserver/webserver-service.yaml
################################
## Airflow Webserver Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: release-name-webserver
  labels:
    tier: airflow
    component: webserver
    release: release-name
    chart: "airflow-1.15.0"
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: webserver
    release: release-name
  ports:
  
    -
      name: airflow-ui
      port: 8080
